use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let channels_path = manifest_dir.join("data/wifi-channels.csv");
    let timeouts_path = manifest_dir.join("config/timeouts.conf");
    let capacity_path = manifest_dir.join("config/daemon-capacity.conf");
    let storage_path = manifest_dir.join("config/storage-policy.conf");

    for path in [
        &channels_path,
        &timeouts_path,
        &capacity_path,
        &storage_path,
    ] {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let mut generated = String::from(
        "// Generated by build.rs from data/wifi-channels.csv and config/*.conf.\n\
         // Do not edit this file directly.\n\n",
    );
    generate_wifi_channels(&channels_path, &mut generated);
    generate_durations(&timeouts_path, &mut generated);
    generate_usize_constants(
        &capacity_path,
        &[
            ("worker_count", "WORKER_COUNT"),
            ("work_queue_capacity", "WORK_QUEUE_CAPACITY"),
            ("control_queue_capacity", "CONTROL_QUEUE_CAPACITY"),
        ],
        &mut generated,
    );
    generate_integer_constants(
        &storage_path,
        &[
            ("history_max_bytes", "HISTORY_MAX_BYTES", "u64"),
            ("history_rotations", "HISTORY_ROTATIONS", "usize"),
        ],
        &mut generated,
    );

    let output =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("generated_config.rs");
    fs::write(&output, generated)
        .unwrap_or_else(|error| panic!("write {}: {error}", output.display()));
}

fn generate_wifi_channels(path: &Path, generated: &mut String) {
    let input = read(path);
    let mut channels = Vec::new();
    let mut frequencies = BTreeSet::new();
    let mut bounds = BTreeMap::<String, (u32, u32)>::new();

    for (index, raw_line) in input.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<_> = line.split(',').map(str::trim).collect();
        if fields.len() != 3 {
            panic!(
                "{}:{}: expected band,frequency_mhz,channel",
                path.display(),
                index + 1
            );
        }
        let band = match fields[0] {
            "2.4" | "5" | "6" => fields[0].to_string(),
            value => panic!(
                "{}:{}: unsupported Wi-Fi band {value:?}",
                path.display(),
                index + 1
            ),
        };
        let frequency = parse_u64(path, index + 1, "frequency", fields[1]) as u32;
        let channel = parse_u64(path, index + 1, "channel", fields[2]) as u32;
        if frequency == 0 || channel == 0 {
            panic!(
                "{}:{}: frequency and channel must be non-zero",
                path.display(),
                index + 1
            );
        }
        if !frequencies.insert(frequency) {
            panic!(
                "{}:{}: duplicate frequency {frequency}",
                path.display(),
                index + 1
            );
        }
        bounds
            .entry(band.clone())
            .and_modify(|(minimum, maximum)| {
                *minimum = (*minimum).min(frequency);
                *maximum = (*maximum).max(frequency);
            })
            .or_insert((frequency, frequency));
        channels.push((frequency, channel));
    }

    for band in ["2.4", "5", "6"] {
        if !bounds.contains_key(band) {
            panic!("{}: missing {band} GHz channel data", path.display());
        }
    }

    generated.push_str("pub(crate) const WIFI_CHANNELS: &[(u32, u32)] = &[\n");
    for (frequency, channel) in channels {
        writeln!(generated, "    ({frequency}, {channel}),").expect("write generated channels");
    }
    generated.push_str("];\n");

    for (band, prefix) in [
        ("2.4", "WIFI_BAND_2_4"),
        ("5", "WIFI_BAND_5"),
        ("6", "WIFI_BAND_6"),
    ] {
        let (minimum, maximum) = bounds[band];
        writeln!(
            generated,
            "pub(crate) const {prefix}_MIN_MHZ: u32 = {minimum};"
        )
        .expect("write generated band minimum");
        writeln!(
            generated,
            "pub(crate) const {prefix}_MAX_MHZ: u32 = {maximum};"
        )
        .expect("write generated band maximum");
    }
    generated.push('\n');
}

fn generate_durations(path: &Path, generated: &mut String) {
    let specs = [
        ("command_poll_interval_ms", "COMMAND_POLL_INTERVAL"),
        ("nmcli_query_timeout_ms", "NMCLI_QUERY_TIMEOUT"),
        ("post_connect_status_wait_ms", "POST_CONNECT_STATUS_WAIT"),
        ("not_found_rescan_timeout_ms", "NOT_FOUND_RESCAN_TIMEOUT"),
        ("activation_timeout_ms", "ACTIVATION_TIMEOUT"),
        ("activation_failure_grace_ms", "ACTIVATION_FAILURE_GRACE"),
        ("wpa_wrong_key_retry_delay_ms", "WPA_WRONG_KEY_RETRY_DELAY"),
        ("secret_timeout_ms", "SECRET_TIMEOUT"),
        (
            "forget_cancellation_timeout_ms",
            "FORGET_CANCELLATION_TIMEOUT",
        ),
        (
            "forget_deactivation_timeout_ms",
            "FORGET_DEACTIVATION_TIMEOUT",
        ),
        (
            "forget_event_poll_interval_ms",
            "FORGET_EVENT_POLL_INTERVAL",
        ),
        ("nl80211_query_timeout_ms", "NL80211_QUERY_TIMEOUT"),
        ("nl80211_poll_interval_ms", "NL80211_POLL_INTERVAL"),
        (
            "networkmanager_event_retry_delay_ms",
            "NETWORKMANAGER_EVENT_RETRY_DELAY",
        ),
    ];
    let values = parse_key_values(path);
    ensure_exact_keys(path, &values, specs.iter().map(|(key, _)| *key));
    for (key, constant) in specs {
        let milliseconds = values[key];
        if milliseconds == 0 {
            panic!("{}: {key} must be non-zero", path.display());
        }
        writeln!(
            generated,
            "pub(crate) const {constant}: ::std::time::Duration = ::std::time::Duration::from_millis({milliseconds});"
        )
        .expect("write generated duration");
    }
    generated.push('\n');
}

fn generate_usize_constants(path: &Path, specs: &[(&str, &str)], generated: &mut String) {
    let typed: Vec<_> = specs
        .iter()
        .map(|(key, constant)| (*key, *constant, "usize"))
        .collect();
    generate_integer_constants(path, &typed, generated);
}

fn generate_integer_constants(path: &Path, specs: &[(&str, &str, &str)], generated: &mut String) {
    let values = parse_key_values(path);
    ensure_exact_keys(path, &values, specs.iter().map(|(key, _, _)| *key));
    for (key, constant, ty) in specs {
        let value = values[*key];
        if value == 0 {
            panic!("{}: {key} must be non-zero", path.display());
        }
        writeln!(generated, "pub(crate) const {constant}: {ty} = {value};")
            .expect("write generated integer");
    }
    generated.push('\n');
}

fn parse_key_values(path: &Path) -> BTreeMap<String, u64> {
    let input = read(path);
    let mut values = BTreeMap::new();
    for (index, raw_line) in input.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (key, value) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("{}:{}: expected key=value", path.display(), index + 1));
        let key = key.trim();
        if key.is_empty() {
            panic!("{}:{}: empty key", path.display(), index + 1);
        }
        let value = parse_u64(path, index + 1, key, value.trim());
        if values.insert(key.to_string(), value).is_some() {
            panic!("{}:{}: duplicate key {key}", path.display(), index + 1);
        }
    }
    values
}

fn ensure_exact_keys<'a>(
    path: &Path,
    values: &BTreeMap<String, u64>,
    expected: impl Iterator<Item = &'a str>,
) {
    let expected: BTreeSet<_> = expected.collect();
    let actual: BTreeSet<_> = values.keys().map(String::as_str).collect();
    if actual != expected {
        let missing: Vec<_> = expected.difference(&actual).copied().collect();
        let unknown: Vec<_> = actual.difference(&expected).copied().collect();
        panic!(
            "{}: missing keys {missing:?}; unknown keys {unknown:?}",
            path.display()
        );
    }
}

fn parse_u64(path: &Path, line: usize, field: &str, value: &str) -> u64 {
    value.parse().unwrap_or_else(|error| {
        panic!(
            "{}:{line}: invalid {field} value {value:?}: {error}",
            path.display()
        )
    })
}

fn read(path: &Path) -> String {
    fs::read_to_string(path).unwrap_or_else(|error| panic!("read {}: {error}", path.display()))
}
