use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR")
            .unwrap_or_else(|| fail("CARGO_MANIFEST_DIR is unavailable")),
    );
    let channels_path = manifest_dir.join("data/wifi-channels.csv");
    let timeouts_path = manifest_dir.join("config/timeouts.conf");
    let capacity_path = manifest_dir.join("config/daemon-capacity.conf");
    let storage_path = manifest_dir.join("config/storage-policy.conf");

    for path in [
        &channels_path,
        &timeouts_path,
        &capacity_path,
        &storage_path,
    ] {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let mut generated = String::from(
        "// Generated by build.rs from data/wifi-channels.csv and config/*.conf.\n\
         // Do not edit this file directly.\n\n",
    );
    generate_wifi_channels(&channels_path, &mut generated);
    generate_durations(&timeouts_path, &mut generated);
    generate_integer_constants(
        &capacity_path,
        &[
            ("worker_count", "WORKER_COUNT", "usize"),
            ("work_queue_capacity", "WORK_QUEUE_CAPACITY", "usize"),
            ("control_queue_capacity", "CONTROL_QUEUE_CAPACITY", "usize"),
        ],
        &mut generated,
    );
    generate_integer_constants(
        &storage_path,
        &[
            ("cache_max_bytes", "CACHE_MAX_BYTES", "u64"),
            ("history_max_bytes", "HISTORY_MAX_BYTES", "u64"),
            ("history_rotations", "HISTORY_ROTATIONS", "usize"),
        ],
        &mut generated,
    );

    let output =
        PathBuf::from(env::var_os("OUT_DIR").unwrap_or_else(|| fail("OUT_DIR is unavailable")))
            .join("generated_config.rs");
    if let Err(error) = fs::write(&output, generated) {
        fail(format!("write {}: {error}", output.display()));
    }
}

fn generate_wifi_channels(path: &Path, generated: &mut String) {
    let input = read(path);
    let mut channels = Vec::new();
    let mut frequencies = BTreeSet::new();
    let mut bounds = BTreeMap::<&str, (u32, u32)>::new();

    for (index, raw_line) in input.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<_> = line.split(',').map(str::trim).collect();
        if fields.len() != 3 {
            fail(at_line(
                path,
                index + 1,
                "expected band,frequency_mhz,channel",
            ));
        }
        let band = match fields[0] {
            "2.4" | "5" | "6" => fields[0],
            value => fail(at_line(
                path,
                index + 1,
                format!("unsupported Wi-Fi band {value:?}"),
            )),
        };
        let frequency = parse_u64(path, index + 1, "frequency", fields[1]) as u32;
        let channel = parse_u64(path, index + 1, "channel", fields[2]) as u32;
        if frequency == 0 || channel == 0 {
            fail(at_line(
                path,
                index + 1,
                "frequency and channel must be non-zero",
            ));
        }
        if !frequencies.insert(frequency) {
            fail(at_line(
                path,
                index + 1,
                format!("duplicate frequency {frequency}"),
            ));
        }
        bounds
            .entry(band)
            .and_modify(|(minimum, maximum)| {
                *minimum = (*minimum).min(frequency);
                *maximum = (*maximum).max(frequency);
            })
            .or_insert((frequency, frequency));
        channels.push((frequency, channel));
    }

    for band in ["2.4", "5", "6"] {
        if !bounds.contains_key(band) {
            fail(format!(
                "{}: missing {band} GHz channel data",
                path.display()
            ));
        }
    }

    generated.push_str("pub(crate) const WIFI_CHANNELS: &[(u32, u32)] = &[\n");
    for (frequency, channel) in channels {
        generated.push_str(&format!("    ({frequency}, {channel}),\n"));
    }
    generated.push_str("];\n");

    for (band, prefix) in [
        ("2.4", "WIFI_BAND_2_4"),
        ("5", "WIFI_BAND_5"),
        ("6", "WIFI_BAND_6"),
    ] {
        let (minimum, maximum) = bounds[band];
        generated.push_str(&format!(
            "pub(crate) const {prefix}_MIN_MHZ: u32 = {minimum};\n\
             pub(crate) const {prefix}_MAX_MHZ: u32 = {maximum};\n"
        ));
    }
    generated.push('\n');
}

fn generate_durations(path: &Path, generated: &mut String) {
    let specs = [
        ("request_timeout_max_ms", "REQUEST_TIMEOUT_MAX"),
        ("command_poll_interval_ms", "COMMAND_POLL_INTERVAL"),
        ("nmcli_query_timeout_ms", "NMCLI_QUERY_TIMEOUT"),
        ("post_connect_status_wait_ms", "POST_CONNECT_STATUS_WAIT"),
        ("not_found_rescan_timeout_ms", "NOT_FOUND_RESCAN_TIMEOUT"),
        ("activation_timeout_ms", "ACTIVATION_TIMEOUT"),
        ("activation_failure_grace_ms", "ACTIVATION_FAILURE_GRACE"),
        ("wpa_wrong_key_retry_delay_ms", "WPA_WRONG_KEY_RETRY_DELAY"),
        ("secret_timeout_ms", "SECRET_TIMEOUT"),
        (
            "forget_cancellation_timeout_ms",
            "FORGET_CANCELLATION_TIMEOUT",
        ),
        (
            "forget_deactivation_timeout_ms",
            "FORGET_DEACTIVATION_TIMEOUT",
        ),
        (
            "forget_event_poll_interval_ms",
            "FORGET_EVENT_POLL_INTERVAL",
        ),
        ("nl80211_query_timeout_ms", "NL80211_QUERY_TIMEOUT"),
        ("nl80211_poll_interval_ms", "NL80211_POLL_INTERVAL"),
        (
            "networkmanager_event_retry_delay_ms",
            "NETWORKMANAGER_EVENT_RETRY_DELAY",
        ),
        (
            "network_snapshot_stale_after_ms",
            "NETWORK_SNAPSHOT_STALE_AFTER",
        ),
        (
            "wifi_band_checkpoint_timeout_ms",
            "WIFI_BAND_CHECKPOINT_TIMEOUT",
        ),
        ("scan_request_interval_ms", "SCAN_REQUEST_INTERVAL"),
        ("scan_retry_delay_ms", "SCAN_RETRY_DELAY"),
        (
            "scan_schedule_poll_interval_ms",
            "SCAN_SCHEDULE_POLL_INTERVAL",
        ),
    ];
    let values = parse_key_values(path);
    ensure_exact_keys(path, &values, specs.iter().map(|(key, _)| *key));
    for (key, constant) in specs {
        let milliseconds = values[key];
        if milliseconds == 0 {
            fail(format!("{}: {key} must be non-zero", path.display()));
        }
        generated.push_str(&format!(
            "pub(crate) const {constant}: ::std::time::Duration = ::std::time::Duration::from_millis({milliseconds});\n"
        ));
    }
    generated.push('\n');
}

fn generate_integer_constants(path: &Path, specs: &[(&str, &str, &str)], generated: &mut String) {
    let values = parse_key_values(path);
    ensure_exact_keys(path, &values, specs.iter().map(|(key, _, _)| *key));
    for (key, constant, ty) in specs {
        let value = values[*key];
        if value == 0 {
            fail(format!("{}: {key} must be non-zero", path.display()));
        }
        generated.push_str(&format!("pub(crate) const {constant}: {ty} = {value};\n"));
    }
    generated.push('\n');
}

fn parse_key_values(path: &Path) -> BTreeMap<String, u64> {
    let input = read(path);
    let mut values = BTreeMap::new();
    for (index, raw_line) in input.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (key, value) = line
            .split_once('=')
            .unwrap_or_else(|| fail(at_line(path, index + 1, "expected key=value")));
        let key = key.trim();
        if key.is_empty() {
            fail(at_line(path, index + 1, "empty key"));
        }
        let value = parse_u64(path, index + 1, key, value.trim());
        if values.insert(key.to_string(), value).is_some() {
            fail(at_line(path, index + 1, format!("duplicate key {key}")));
        }
    }
    values
}

fn ensure_exact_keys<'a>(
    path: &Path,
    values: &BTreeMap<String, u64>,
    expected: impl Iterator<Item = &'a str>,
) {
    let expected: BTreeSet<_> = expected.collect();
    let actual: BTreeSet<_> = values.keys().map(String::as_str).collect();
    if actual == expected {
        return;
    }
    let missing: Vec<_> = expected.difference(&actual).copied().collect();
    let unknown: Vec<_> = actual.difference(&expected).copied().collect();
    fail(format!(
        "{}: missing keys {missing:?}; unknown keys {unknown:?}",
        path.display()
    ));
}

fn parse_u64(path: &Path, line: usize, field: &str, value: &str) -> u64 {
    value.parse().unwrap_or_else(|error| {
        fail(at_line(
            path,
            line,
            format!("invalid {field} value {value:?}: {error}"),
        ))
    })
}

fn read(path: &Path) -> String {
    fs::read_to_string(path)
        .unwrap_or_else(|error| fail(format!("read {}: {error}", path.display())))
}

fn at_line(path: &Path, line: usize, message: impl std::fmt::Display) -> String {
    format!("{}:{line}: {message}", path.display())
}

fn fail(message: impl std::fmt::Display) -> ! {
    eprintln!("cargo:error={message}");
    std::process::exit(1)
}
